In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# download data set: https://drive.google.com/file/d/13nw-uRXPY8XIZQxKRNZ3yYlho-CYm_Qt/view
# info: https://archive.ics.uci.edu/ml/datasets/banknote+authentication

In [3]:
# load data
bankdata = pd.read_csv("./bill_authentication.csv")

In [4]:
# see the data
bankdata.shape

(1372, 5)

In [5]:
# see head
bankdata.head()  

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [6]:
# data processing
X = bankdata.drop('Class', axis=1)  
y = bankdata['Class']  

In [7]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  

In [8]:
# train the SVM
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [9]:
# predictions
y_pred = svclassifier.predict(X_test) 

In [10]:
# Evaluate model
from sklearn.metrics import classification_report, confusion_matrix  
print('Confusion Matrix of Linear Kernel')
print(confusion_matrix(y_test,y_pred))  

Confusion Matrix of Linear Kernel
[[144   1]
 [  0 130]]


In [11]:
print('Classification Report of Linear Kernel')
print(classification_report(y_test,y_pred))

Classification Report of Linear Kernel
             precision    recall  f1-score   support

          0       1.00      0.99      1.00       145
          1       0.99      1.00      1.00       130

avg / total       1.00      1.00      1.00       275



In [12]:
def import_iris():
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

    # Assign colum names to the dataset
    colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

    # Read dataset to pandas dataframe
    irisdata = pd.read_csv(url, names=colnames) 

    # process
    X = irisdata.drop('Class', axis=1)  
    y = irisdata['Class']  

    # train
    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [13]:
def polynomial_kernel():
    # TODO
    # NOTE: use 8-degree in the degree hyperparameter. 
    # Trains, predicts and evaluates the model
    from sklearn.svm import SVC 
    svclassifier = SVC(kernel='poly', degree=8)  
    svclassifier.fit(X_train, y_train) 
    # predictions
    y_pred = svclassifier.predict(X_test) 
    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print('Confusion Matrix of Polynomial Kernel')
    print(confusion_matrix(y_test,y_pred))
    print('Classification Report of Polynomial Kernel')
    print(classification_report(y_test,y_pred))

In [14]:
def gaussian_kernel():
    # TODO
    # Trains, predicts and evaluates the model
    from sklearn.svm import SVC 
    svclassifier = SVC(kernel='rbf')  
    svclassifier.fit(X_train, y_train) 
    # predictions
    y_pred = svclassifier.predict(X_test) 
    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print('Confusion Matrix of Gaussian Kernel')
    print(confusion_matrix(y_test,y_pred))
    print('Classification Report of Gaussian Kernel')
    print(classification_report(y_test,y_pred))

In [15]:
def sigmoid_kernel():
    # TODO
    # Trains, predicts and evaluates the model
    from sklearn.svm import SVC 
    svclassifier = SVC(kernel='sigmoid')  
    svclassifier.fit(X_train, y_train) 
    # predictions
    y_pred = svclassifier.predict(X_test) 
    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print('Confusion Matrix of Sigmoid Kernel')
    print(confusion_matrix(y_test,y_pred))
    print('Classification Report of Sigmoid Kernel')
    print(classification_report(y_test,y_pred))

In [16]:
def test():
    import_iris()
    polynomial_kernel()
    gaussian_kernel()
    sigmoid_kernel()

In [17]:
test()

Confusion Matrix of Polynomial Kernel
[[141   4]
 [  0 130]]
Classification Report of Polynomial Kernel
             precision    recall  f1-score   support

          0       1.00      0.97      0.99       145
          1       0.97      1.00      0.98       130

avg / total       0.99      0.99      0.99       275

Confusion Matrix of Gaussian Kernel
[[145   0]
 [  0 130]]
Classification Report of Gaussian Kernel
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       145
          1       1.00      1.00      1.00       130

avg / total       1.00      1.00      1.00       275

Confusion Matrix of Sigmoid Kernel
[[100  45]
 [ 64  66]]
Classification Report of Sigmoid Kernel
             precision    recall  f1-score   support

          0       0.61      0.69      0.65       145
          1       0.59      0.51      0.55       130

avg / total       0.60      0.60      0.60       275

